### PR TITLE
Added connect_ap.lua, editor.lua and file_copy.lua example

### PR DESCRIPTION
**Pull request by moononournation**
Hi, your node-httpserver is great! I would like to develop more base on this.

Here is some details I start working:
http://www.instructables.com/id/IoT-Development-With-Mobile-Directly/

### CODE REVIEW

**Comment by marcoskirsch** [comment]
```
Hi, your node-httpserver is great! I would like to develop more base on this.
```

Thanks! I'm glad people are using it and helping with improvements.

Feedback on the pull request:
- adhoc.lua should not have been added, right?
- connect_ap.lua is neat. It should be pretty easy to change the form to a [radio button](http://www.w3schools.com/html/tryit.asp?filename=tryhtml_form_radio)
- I worry about the security implications of editor.lua. Given that nodemcu-httpserver does not require authentication by default, and is always unencrypted, putting editor.lua in the examples seems like too much. My suggestion: Leave the code that creates the file commented out and explain that it needs to be uncommented in order to work, including the security implications of such. That seems a lot more responsible.

Since you're adding two scripts, it would be better to do two pull requests, but I leave that to you.

Thanks!

**Comment by moononournation** [comment]
ok, let me start from the beginning. I will try to enhancement the requset
function first:
1. add user to req dict
2. add error handling (pcall) while calling lua in http folder

thx
Leung

Marcos notifications@github.com 於 2016年5月23日星期一 寫道：

**Comment by moononournation** [comment]
I have just finished the NodeMCU WebIDE instructables, please take a look:
http://www.instructables.com/id/NodeMCU-WebIDE/

Leung

2016-05-23 16:47 GMT+08:00 moon moon@pubws.com:

**Comment by marcoskirsch** [comment]
> ok, let me start from the beginning. I will try to enhancement the requset
> function first:
> 
> add user to req dict

I have added this is now in master 
https://github.com/marcoskirsch/nodemcu-httpserver/pull/100

> add error handling (pcall) while calling lua in http folder

This would be a great PR!

**Comment by HHHartmann** [comment]
since the lua scripts are called within a coroutine, erros are cought already and the coroutine returns with status "error". So this could be made nicer but this would also take up memory.

**Pull request closed without merging**
