### PR TITLE
Fix the problem with the more modern SDK only allowing one outstanding connection:send

### PR DESCRIPTION
**Pull request by pjsg**
This fixes the problem that I reported in an almost backwards compatible way. The only change is that file serving functions must _NOT_ call coroutine.yield()  This is all handled inside the :send method.

This works for me using the current dev build.....

### CODE REVIEW

**Comment by marcoskirsch** [comment]
Did you get a chance to test out the bundled examples?

**Comment by pjsg** [comment]
Yes -- I checked all the examples. I fixed a bug in node_info: it would try and concat a nil value under some circumstances. Also, for reasons that I don't understand, it would reset my nodemcu until I changed the declaration of the returned variables for node.info() to be local. I suspect that there is some underlying bug in the firmware, but it isn't obvious to me what it is. It is something to do with the concatenation operator and the global variables. The line:

local x = majorVer.."."..minorVer.."."..devVer

causes the trap (if the majorVer etc are globals. Works if they are locals).

**Comment by dfeinzeig** [comment]
Did you mean to include http/Thumbs.db?

**Comment by pjsg** [comment]
Argh! Thumbs.db removed as well.

**Comment by marcoskirsch** [comment]
Thanks!

**Pull request merged**
