### PR TITLE
Upload form for nodemcu-httpserver

### PR DESCRIPTION
**Pull request by ATAMAH**
Now you can update your files in /http directory of your tiny webserver
over Wi-Fi!

- Drag&drop or browse one or multiple files.
- List uploaded files.
- Delete files.
- Automatically rename files to http/(filename)
- Automatically compile .lua files.
- Shows total/used memory.

You must compile upload.lua file!

Have some bugs but works pretty well even for uploading lot of files.

### CODE REVIEW

**Comment by ATAMAH** [comment]
Seems like it cant handle the "garage_door_opener.html" file name. Too long.

**Comment by marcoskirsch** [comment]
Thanks for contributing!

I have several comments:

The changes to cars.html show how to work around a limitation with ESP8266/nodemcu-firmware/nodemcu-httpserver. As such it's great.
I'd rather keep the old example cars.html as-is, because it illustrates the limitation and provides a way for testing potential fixes in the server itself (not workarounds in the HTML).
How about leaving cars.html alone, but adding your example as cars-prog.html (prog for progressive) or something like that? Then modify index.html to link to it and explain that it provides a workaround for said problem. This should be its own pull request with its own description.

I'm still going over the upload stuff. It's certainly very useful. Is it meant to be an "example" like everything else inside the http/ directory? Or do you intend for this to be part of the "core" server? Depending on this I have other observations.

**Comment by ATAMAH** [comment]
Hello Marcos.

Sorry I didnt know that all changes comes as single pull request. 

About cars.html I will better make demo with loading images, scripts, styles as many files for single page.

Upload form is for using as a part of the httpserver. I've made it months ago and I want to make a little contribution to your project. The limitation that the upload script loads files only to http/ folder is for keep server stable.

**Comment by marcoskirsch** [comment]
I've merged the upload form, it's very neat!
I think there's value in your cars.html example. Do you want another pull request? Or should I grab it from here and recreate?

**Comment by ATAMAH** [comment]
Thank you for merge.

I will make another pull request.

**Pull request closed without merging**
