### PR TITLE
remove the coroutine feature

### PR DESCRIPTION
**Pull request by olgaW**
I have test the server under NodeMCU frameware 0.9.5. It looks like the coroutine doesn't work very well between multi 'onSent' events. Does this feature works good under higher version? 
In my commit I removed coroutine feature from code, and I tested that it still works well. Please check~

### CODE REVIEW

**Comment by pastukhov** [comment]
Can your code serve files bigger that 3k?

**Comment by olgaW** [comment]
@pastukhov Do you mean the .lua file size bigger than 3K or the output of .lua file bigger than 3K?

**Comment by pastukhov** [comment]
@olgaW 
Output

**Comment by pastukhov** [comment]
Look at https://github.com/nodemcu/nodemcu-firmware/issues/211

**Comment by olgaW** [comment]
@pastukhov I have not tested serve script way. Since the chip's buffer size is very small, we can try to output the content to tmp file. After that we can read and send it little by little.

**Comment by olgaW** [comment]
@pastukhov In above code, it read all file content in once. If your file content size over chip's sent buffer, chip will reboot.

**Comment by marcoskirsch** [comment]
@olgaW I wouldn't create temp files in nodemcu, the file system is not as robust as you'd think.
The coroutine is necessary for serving files larger than the network FIFO in the chip (~3KB), it allows the server to send in smaller chunks.

You say things don't work well, but you don't describe how? In most likelihood, it's a memory problem. It appears that a recent nodemcu build freed up a good amount of RAM. I'd give that a shot and report back.

**Comment by olgaW** [comment]
Tmp file is just maybe. The problem looks like that in multi connection the follow connection's onSent will course brfore connection's onSent lost. I tested the index.html in low speed environment. When gif's sending begins before index.html's outputing finished, the index.html's onSent event will lost.

**Comment by marcoskirsch** [comment]
I tried dev096 integer build which has a lot more free RAM and it works great. I'm going to close this as I believe it's an incorrect change.

**Pull request closed without merging**
