### PR TITLE
Serve static pages efficiently. Fix #53

### LINKED ISSUE #53: Can't handle page with embedded images
The server quickly runs out of memory and crashes if a page with a few embedded images is requested. See example cars.html

```
  Requested URI: /cars.html
  Requested URI: /cars-mas.jpg
  Requested URI: /cars-ferrari.jpg
  Requested URI: /cars-lambo.jpg
  PANIC: unprotected error in call to Lua API (not enough memory)
  ����1�)m�1�)�!�����B
```

### PR DESCRIPTION
**Pull request by HHHartmann**
Allows to load up to 5 static URLs at the same time. 
The limit of 5 seems to be imposed by the system. 

This should at least partially fix #53

### CODE REVIEW

**Comment by HHHartmann** [comment]
anybody willing to review this?

**Comment by marcoskirsch** [comment]
I will soon, my bad.

**Comment by Fractal147** [comment]
Err, while this achieves the goal, can't you achieve most changes from within httpserver-static.lua? You can access the socket within bufferedConnection, and yield there - no buffer used, no problem.

The chunks are 1024 big, but have no buffer to worry about since it's never filled
There are further things to do, like setting req=nil in httpserver.lua for static, but this seems pretty efficient to me - and works with 5 cars on chrome desktop.
See PR #123

**Comment by HHHartmann** [comment]
The main advantage in this PR is to get rid of the coroutine overhead which seems to be quite large.
The rest might be done differently. But what seems important to me is that the memory footprint between sending chunks is minimal (only filename and position) which helps executing several requests at the same time.

**Pull request merged**
