### PR TITLE
Four enhancements. Two bug fixes.

### PR DESCRIPTION
**Pull request by CharlesScoville**
Specific Changes
----------

_Bug Fixes:_
Updated `Hello_world.txt` to have the UTF-8 BOM. This lets browsers properly display embedded unicode when sent by the server as *.txt file.

[Edit: apparently still bugged.] Added code to initialize GPIO to sane state on boot. Most useful for the garage_door_opener example.

_Enhancements:_
Moved most of the code out of `init.lua`, transforming `init.lua` to a stub that launches the main code.

New init stub script automatically finds and uses *.lua or *.lc init file as appropriate. Preference is for *.lua variety, as that is what you upload when playing with changes. The stub will gracefully fall back to lua prompt if neither file is found.

Added a non-blocking delay to the init stub to allow for easy recovery from other script misbehaving. A five second window is allowed for command injection before the rest of the script(s) gets to run.

Moved main init code into a new, separate file called `_init_.lua` to be called from stub. This allows for the meat of the init code to be compiled if desired, greatly reducing size and increasing speed. Saves about 1K ROM as of now.

Added CPU speed switch code to `_init_.lua` Presumably NodeMCU boots to 80Mhz core clock. node.setcpufreq() can be used to change that to 160Mhz, for a solid boos in performance. Wikipedia says this is an overclock, but I'm pretty sure it's not. I believe it's a power saving feature.

Notes
----------

The GPIO initialization is done for GPIO0 and GPIO2, as that's what's broken out on the ESP-01 boards. Other boards will require edits to this code. (~Line 4 of `_init_.lua`.)

Not sure if this should be merged into master, or if maybe it should go into dev. I just pull requested to where I forked from, but your the boss.

All this needs tested for conformance, of course, as I can't represent every setup.

### CODE REVIEW

**Comment by CharlesScoville** [comment]
Hummm.... a fresh re-flashing and upload shows that my GPIO fix isn't working, at least not like it was. Guna need to do some more work/testing on this.

**Comment by ATAMAH** [comment]
> Added line breaks to space out hyperlinks.

Better use styles:

```
@media only screen and (max-device-width: 480px) {
  a {
    margin-bottom: 5px;
  }
}
```

**Comment by CharlesScoville** [comment]
>Better use styles:

Agreed. (Though your example appears to need to be applied to the `<li>` tag to be effective.)

More than just this style change needs to be made honestly. The text renders unreasonably small on my perfectly normal 1080p screen. With `body { font-size: 200%; }` it's about perfect. I guess the decision to do it the current way was because it was easier to do and smaller?

I may add something for this too when I'm done testing it on some other machines/browsers.

**Comment by marcoskirsch** [comment]
Would it be possible to break this up in separate PRs, one for each logical change?
Thanks!

**Comment by CharlesScoville** [comment]
Sorry I haven't got on this right away, computer borked. Using a backup pc, but haven't had access to the HDD that has my dev stuff. (Also, this pc might as well be made of wood.)

**Comment by CharlesScoville** [comment]
OK. I'm trying to get on this ASAP. However, as I'm not sure exactly what will be best, I could use some advice/direction before I do. 

The way I see it I could...
1) Make new PRs for each issue, _then_ delete this one.
2) Delete this PR, _then_ remake these PRs separately.
3) Delete everything, resync with the main branch, make fresh changes and PRs for them. (a "do over")

Not necessarily sure how to go about any one of these either. (Not new to coding/EEing, just new to github.)

**Comment by marcoskirsch** [comment]
Do the first option, and make sure there are no conflicts in your PRs. This is good timing, I hope to work on this project on this long weekend. Thanks!

**Comment by HHHartmann** [comment]
Hi, I like the idea of having a small init.lua file. I was also preparing a commit in that direction.
I was going to divide the init.lua in two parts, one for preparing the http server (precompile, GPIO and the like) and one for setting up the connection.
I also was having other projects on my ESP, like an ftp server or a data collector which also need initialization. So I was naming the files more specifically, like httpserver-wifisetup.lua and httpserver-init.lua.
So if you like, you could go that direction while you are at it.
Just my 2c

**Comment by marcoskirsch** [comment]
> Hi, I like the idea of having a small init.lua file.

I started work on this. It's not quite working yet, but you can see the general direction and maybe do your own modifications here:
https://github.com/marcoskirsch/nodemcu-httpserver/tree/httpserver-init.lua

**Comment by marcoskirsch** [comment]
https://github.com/marcoskirsch/nodemcu-httpserver/pull/95
Covers node-info.lua improvements.

https://github.com/marcoskirsch/nodemcu-httpserver/pull/94
Covers moving code outside init.lua. Doesn't do everything you did here, however, rather it's functionally equivalent to what we had.

**Comment by CharlesScoville** [comment]
Hey, sorry I'm late, dev electronics are/were giving me grief.

So, I'm looking at the most recent commits to the repo and it seems you went ahead and did pretty much everything that I did and then some? Is there any more reason for me to follow through with this, or should this PR just be closed?

It would be great if you got everything settled without me since I can't seem to make git do what you're asking anyway. However if you still need me to make this work I can keep trying to figure it out.

**Comment by marcoskirsch** [comment]
The init delay and doesn’t belong in the project IMHO so I’ll close.
I still want to try the CPU speed trick, but I was thinking it would be best to ramp I it up when serving a page dynamically, rather than leave it at its fast setting all the time.

**Pull request closed without merging**
