### PR TITLE
Move server code to LFS

### PR DESCRIPTION
**Pull request by matsievskiysv**
This PR moves server code to [LFS](https://nodemcu.readthedocs.io/en/master/en/lfs/). It saves about 10k of chip ram.
It should not be merged into master branch, but to the new one instead.

### CODE REVIEW

**Comment by marcoskirsch** [comment]
This PR seems really useful but has merge conflicts.
@seregaxvm it's been a long time, but would you be willing to resolve this?

**Comment by matsievskiysv** [comment]
Done. Unfortunately, testing this would be problematic since `nodemcu-uploader` doesn't work with newer nodemcu firmware.

**Comment by marcoskirsch** [comment]
> Done. Unfortunately, testing this would be problematic since nodemcu-uploader doesn't work with newer nodemcu firmware.

Is there a different tool we should be using? Please comment on #127

**Comment by marcoskirsch** [comment]
Looking at the diff... can you confirm that this change requires users to build their own firmware using Docker and this will render the server unusable with the default images?

Or can you build the image using https://nodemcu-build.com ?

**Comment by matsievskiysv** [comment]
I thought that this code would be in a different branch for firmware with `LFS` support. So there would be two branches (something like `master` and `lfs`).
Do you think that this code should be changed to determine firmware type in runtime?

> Or can you build the image using https://nodemcu-build.com ?

<https://nodemcu-build.com> allows to build image with LFS support. I will test it just to be sure.

**Comment by HHHartmann** [comment]
In my opinion separating this on two branches will do no good. 
Every feature would have to be copied over to the other branch. That will be hard to do. 
The code itself should not differ. Just the build targets and init.lua

**Comment by matsievskiysv** [comment]
Changed code so it could work with both SPIFFS and LFS. It will apply `lfs.img` if available. If not, it will run code from SPIFFS. I didn't touch `Makefile` though.
Tested only on `dev` branch with docker and cloud firmware builds.

**Comment by marcoskirsch** [comment]
>  I didn't touch Makefile though.

Why is this relelvant?

**Review by marcoskirsch — APPROVED** [review]
I get the impression that this moves the nodemcu-httpserver project away from its goals of being simple and easy for nodemcu beginners. That said, I've been away for long enough to lose track of where nodemcu has been going and trust the judgement of seregaxvm who's on top of it.

I will merge.

**Comment by matsievskiysv** [comment]
Changes to Makefile are needed because server files are now in separate folder.
I will get back to it as soon as nodemcu-uploader will be fixed. It is being discussed in <https://github.com/nodemcu/nodemcu-firmware/issues/2963>

**Comment by marcoskirsch** [comment]
Ok great, if you don't mind please open an issue about it.

**Pull request merged**
